

title: mask on — anti surveillance protest guide
email: your-email@example.com
description: anti surveillance protest guide
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: 
plugins:
  - jekyll-feed
  - jekyll-srcset

kramdown:
  parse_block_html: true
permalink: pretty
collections:
  before:
    output: true
  during:
    output: true
  after:
    output: true
  resources:
    output: true

# defaults:
#   -
#     scope:
#       path: ""
#       type: "paintings"
#     values:
#       layout: "painting"